version: '3'
services:
  postgresdb:
    image: llearnell/multidbpg
    restart: unless-stopped
    #mem_limit: 512M  
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - postgresdata13:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/01init-invidious-db.sh
    environment:
      #- singledb.env
      #- POSTGRES_USERS= "nextcloud:79ee2d65ff272f51abcfbe817cc58aac|kemal:FiW6BsQgxyUErPVgHB2p"
      POSTGRES_USERS: "nextcloud:79ee2d65ff272f51abcfbe817cc58aac|kemal:kemal"
      #POSTGRES_DATABASES: "nextcloud:nextcloud|invidious:kemal"
      POSTGRES_DATABASES: "invidious:kemal|nextcloud:nextcloud"
      POSTGRES_DB: invidious
      POSTGRES_PASSWORD: kemal
      POSTGRES_USER: kemal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      

  invidious:
    image: llearnell/invidious-container:latest
      #mem_limit: 2048M  
    deploy:
      resources:
        limits:
          memory: 1024M

    restart: unless-stopped
    #logging:
    #  driver: none
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          user: kemal
          #password: FiW6BsQgxyUErPVgHB2p
          password: kemal
          host: postgresdb
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: false
        disable_proxy:
          - downloads
        domain:
    depends_on:
      - postgresdb

  app:
    image: nextcloud:apache
    restart: unless-stopped
    #logging:
    #    driver: none
    volumes:
      - nextcloud:/var/www/html
        #- /root/nxtcld/app/www.conf:/usr/local/etc/php-fpm.d/www.conf
        #- /root/nxtcld/app/php.ini-production:/usr/local/etc/php/php.ini-production
        #- /root/nxtcld/app/php.ini-development:/usr/local/etc/php/php.ini-development
        #- /root/nxtcld/app/php.ini-production:/usr/local/etc/php/php.ini
    environment:
      - POSTGRES_HOST=postgresdb
    expose:
      - 9000
    env_file:
      - db.env
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - postgresdb
        #networks:
        #- multidb


# whoogle:
#   image: "benbusby/whoogle-search:latest"
#   container_name: "whoogle"
#   logging:
#       driver: none
#   volumes:
#       - "./config/whoogle/languages.json:/usr/src/app/app/misc/languages.json"
#       - "./config/whoogle/countries.json:/usr/src/app/app/misc/countries.json"
#   environment:
#       - WHOOGLE_ALT_YT=tube.sensely.tk
#         #VIRTUAL_HOST: "sensely.ml,www.sensely.ml"
#         #VIRTUAL_PORT: "5000"
#   restart: "unless-stopped"
#   ports:
#     - "127.0.0.1:5000:5000"

# advisor:
#   image: gcr.io/cadvisor/cadvisor:latest
#   container_name: cadvisor
#   volumes:
#     - /:/rootfs:ro
#     - /var/run/docker.sock:/var/run/docker.sock:ro
#     - /var/run:/var/run:rw
#     - /sys:/sys:ro
#     - /var/lib/docker:/var/lib/docker:ro
#     - /sys/fs/cgroup:/cgroup:ro
#     - /dev/disk/:/dev/disk:ro
#   deploy:
#     resources:
#       limits:
#         memory: 128M
#   command:
#     - '-housekeeping_interval=60s'
#     - '-docker_only=true'
#   restart: unless-stopped
#   devices:
#     - /dev/kmsg:/dev/kmsg
#   security_opt:
#     - no-new-privileges:true
#   ports:
#     - "127.0.0.1:8080:8080"
    #labels:
    # group: "monitoring"
    # host.name: "${HOST_NAME}"        

volumes:
  postgresdata13:
  nextcloud:


networks:
  multidb:
